application: percolate-coffeeapi
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /appengineadmin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
