version: 2
jobs:
  flake8:
    docker:
      - image: python:2.7
    steps:
      - run: pip install flake8
      - checkout
      - run: flake8 .

workflows:
  version: 2
  coffeeapi:
    jobs:
      - flake8
